"""
Django settings for gestionale project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path


# ============================================================
# PERCORSI
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# AMBIENTE
# ============================================================

IS_PYTHONANYWHERE = "PYTHONANYWHERE_DOMAIN" in os.environ


# ============================================================
# SICUREZZA
# ============================================================

SECRET_KEY = 'django-insecure-zy!8_lcm@$2=s3fy9)7+01s4q8vh!)azczla2qgnq&5v+e(uo%'

if IS_PYTHONANYWHERE:
    DEBUG = False
    ALLOWED_HOSTS = [
        ".pythonanywhere.com",
    ]
else:
    DEBUG = True
    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
        "192.168.1.178",
    ]


# ============================================================
# APPLICAZIONI
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'magazzino',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URL
# ============================================================

ROOT_URLCONF = 'gestionale.urls'


# ============================================================
# TEMPLATE
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'gestionale.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

if IS_PYTHONANYWHERE:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

else:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "gestionale",
            "USER": "luigi",
            "PASSWORD": "luigi",
            "HOST": "127.0.0.1",
            "PORT": "3306",
        }
    }


# ============================================================
# VALIDAZIONE PASSWORD
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================
# INTERNAZIONALIZZAZIONE
# ============================================================

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True


# ============================================================
# FILE STATICI
# ============================================================

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# ============================================================
# EMAIL
# ============================================================

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}