# Generated by Django 6.1 on 2026-08-31 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magazzino', '0070_materiali_nc_tracciabilita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequenza', models.PositiveSmallIntegerField()),
                ('stato', models.CharField(choices=[('DA_AVVIARE', 'Da avviare'), ('IN_CORSO', 'In corso'), ('IN_ATTESA', 'In attesa'), ('BLOCCATA', 'Bloccata'), ('COMPLETATA', 'Completata'), ('SALTATA', 'Saltata'), ('ANNULLATA', 'Annullata')], db_index=True, default='DA_AVVIARE', max_length=12)),
                ('iniziata_il', models.DateTimeField(blank=True, null=True)),
                ('completata_il', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('ordine', 'sequenza'),
            },
        ),
        migrations.CreateModel(
            name='LineaProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('attiva', models.BooleanField(default=True)),
                ('descrizione', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('codice',),
            },
        ),
        migrations.CreateModel(
            name='StazioneLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('PREPARAZIONE', 'Preparazione'), ('TRASFORMAZIONE', 'Trasformazione'), ('CONFEZIONAMENTO', 'Confezionamento'), ('CONTROLLO', 'Controllo'), ('ALTRO', 'Altro')], max_length=20)),
                ('attiva', models.BooleanField(default=True)),
                ('configurazione', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('codice',),
            },
        ),
        migrations.CreateModel(
            name='ConsumoMateriale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=6, max_digits=14)),
                ('stato', models.CharField(choices=[('PRENOTATO', 'Prenotato'), ('PRELEVATO', 'Prelevato'), ('CONSUMATO', 'Consumato'), ('REINTEGRATO', 'Reintegrato'), ('SCARTATO', 'Scartato')], default='PRENOTATO', max_length=12)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumi_produzione_v2', to='magazzino.articolo')),
                ('lotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumi_produzione_v2', to='magazzino.lotto')),
                ('ubicazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumi_produzione_v2', to='magazzino.ubicazione')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiali', to='produzione_v2.faseproduzione')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causale', models.CharField(max_length=30)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collegamenti_movimento', to='produzione_v2.consumomateriale')),
                ('movimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collegamento_produzione_v2', to='magazzino.movimento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdineProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=40, unique=True)),
                ('quantita_pianificata', models.DecimalField(decimal_places=3, max_digits=14)),
                ('stato', models.CharField(choices=[('PIANIFICATO', 'Pianificato'), ('PRONTO', 'Pronto'), ('IN_CORSO', 'In corso'), ('SOSPESO', 'Sospeso'), ('BLOCCATO_NC', 'Bloccato per NC'), ('COMPLETATO', 'Completato'), ('ANNULLATO', 'Annullato'), ('ABORTITO', 'Abortito')], db_index=True, default='PIANIFICATO', max_length=15)),
                ('priorita', models.PositiveSmallIntegerField(default=0)),
                ('pianificato_per', models.DateField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('avviato_il', models.DateTimeField(blank=True, null=True)),
                ('completato_il', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini_produzione_v2_creati', to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='produzione_v2.lineaproduzione')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini_produzione_v2', to='magazzino.articolo')),
            ],
            options={
                'ordering': ('-priorita', 'pianificato_per', 'codice'),
            },
        ),
        migrations.AddField(
            model_name='faseproduzione',
            name='ordine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fasi', to='produzione_v2.ordineproduzione'),
        ),
        migrations.CreateModel(
            name='EventoProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('dati', models.JSONField(blank=True, default=dict)),
                ('registrato_il', models.DateTimeField(auto_now_add=True)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi_produzione_v2', to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='produzione_v2.faseproduzione')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='produzione_v2.ordineproduzione')),
            ],
            options={
                'ordering': ('registrato_il', 'id'),
            },
        ),
        migrations.AddField(
            model_name='consumomateriale',
            name='ordine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiali', to='produzione_v2.ordineproduzione'),
        ),
        migrations.CreateModel(
            name='PassaggioLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveSmallIntegerField()),
                ('obbligatoria', models.BooleanField(default=True)),
                ('configurazione', models.JSONField(blank=True, default=dict)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passaggi', to='produzione_v2.lineaproduzione')),
                ('stazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passaggi_linea', to='produzione_v2.stazionelavoro')),
            ],
            options={
                'ordering': ('linea', 'ordine'),
            },
        ),
        migrations.AddField(
            model_name='faseproduzione',
            name='passaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fasi', to='produzione_v2.passaggiolinea'),
        ),
        migrations.CreateModel(
            name='DefinizioneControllo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=120)),
                ('tipo_dato', models.CharField(choices=[('DECIMALE', 'Numero decimale'), ('INTERO', 'Numero intero'), ('BOOLEANO', 'Sì/No'), ('TESTO', 'Testo')], max_length=12)),
                ('obbligatorio', models.BooleanField(default=True)),
                ('unita_misura', models.CharField(blank=True, max_length=20)),
                ('regole', models.JSONField(blank=True, default=dict)),
                ('ordine', models.PositiveSmallIntegerField(default=1)),
                ('stazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlli', to='produzione_v2.stazionelavoro')),
            ],
            options={
                'ordering': ('stazione', 'ordine', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UnitaProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('codice', models.CharField(max_length=50)),
                ('quantita', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('stato', models.CharField(choices=[('CREATA', 'Creata'), ('IN_LAVORAZIONE', 'In lavorazione'), ('CONFORME', 'Conforme'), ('ALLERTA', 'In allerta'), ('QUARANTENA', 'In quarantena'), ('REINTEGRATA', 'Reintegrata'), ('SCARTATA', 'Scartata'), ('ANNULLATA', 'Annullata')], default='CREATA', max_length=15)),
                ('metadati', models.JSONField(blank=True, default=dict)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unita', to='produzione_v2.faseproduzione')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unita', to='produzione_v2.ordineproduzione')),
                ('origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivate', to='produzione_v2.unitaproduzione')),
            ],
        ),
        migrations.CreateModel(
            name='RilevazioneControllo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.JSONField()),
                ('esito', models.CharField(choices=[('CONFORME', 'Conforme'), ('ALLERTA', 'Allerta'), ('NON_CONFORME', 'Non conforme'), ('NON_APPLICABILE', 'Non applicabile')], max_length=17)),
                ('rilevato_il', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('definizione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rilevazioni', to='produzione_v2.definizionecontrollo')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rilevazioni', to='produzione_v2.faseproduzione')),
                ('rilevato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlli_produzione_v2', to=settings.AUTH_USER_MODEL)),
                ('unita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rilevazioni', to='produzione_v2.unitaproduzione')),
            ],
        ),
        migrations.CreateModel(
            name='NonConformita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=50, unique=True)),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('IN_GESTIONE', 'In gestione'), ('CHIUSA', 'Chiusa')], default='APERTA', max_length=12)),
                ('motivo', models.TextField()),
                ('esito', models.CharField(blank=True, choices=[('REINTEGRO', 'Reintegro'), ('SCARTO', 'Scarto'), ('DEROGA', 'Deroga'), ('ANNULLAMENTO', 'Annullamento')], max_length=12)),
                ('azione', models.TextField(blank=True)),
                ('aperta_il', models.DateTimeField(auto_now_add=True)),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
                ('aperta_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nc_produzione_v2_aperte', to=settings.AUTH_USER_MODEL)),
                ('chiusa_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nc_produzione_v2_chiuse', to=settings.AUTH_USER_MODEL)),
                ('consumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='produzione_v2.consumomateriale')),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='produzione_v2.faseproduzione')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='produzione_v2.ordineproduzione')),
                ('unita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='produzione_v2.unitaproduzione')),
            ],
        ),
        migrations.CreateModel(
            name='AssegnazioneOperatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assegnato_il', models.DateTimeField(auto_now_add=True)),
                ('terminato_il', models.DateTimeField(blank=True, null=True)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni_produzione_v2', to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni', to='produzione_v2.faseproduzione')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fase', 'operatore'), name='v2_unica_assegnazione_operatore_fase')],
            },
        ),
        migrations.AddConstraint(
            model_name='ordineproduzione',
            constraint=models.CheckConstraint(condition=models.Q(('quantita_pianificata__gt', 0)), name='v2_quantita_ordine_positiva'),
        ),
        migrations.AddConstraint(
            model_name='consumomateriale',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__gt', 0)), name='v2_quantita_materiale_positiva'),
        ),
        migrations.AddConstraint(
            model_name='faseproduzione',
            constraint=models.UniqueConstraint(fields=('ordine', 'sequenza'), name='v2_unica_sequenza_fase_ordine'),
        ),
        migrations.AddConstraint(
            model_name='faseproduzione',
            constraint=models.UniqueConstraint(fields=('ordine', 'passaggio'), name='v2_unico_passaggio_fase_ordine'),
        ),
        migrations.AddConstraint(
            model_name='passaggiolinea',
            constraint=models.UniqueConstraint(fields=('linea', 'ordine'), name='v2_unico_ordine_stazione_linea'),
        ),
        migrations.AddConstraint(
            model_name='passaggiolinea',
            constraint=models.UniqueConstraint(fields=('linea', 'stazione'), name='v2_unica_stazione_linea'),
        ),
        migrations.AddConstraint(
            model_name='passaggiolinea',
            constraint=models.CheckConstraint(condition=models.Q(('ordine__gt', 0)), name='v2_ordine_passaggio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='definizionecontrollo',
            constraint=models.UniqueConstraint(fields=('stazione', 'codice'), name='v2_unico_controllo_stazione'),
        ),
        migrations.AddConstraint(
            model_name='unitaproduzione',
            constraint=models.UniqueConstraint(fields=('ordine', 'codice'), name='v2_unico_codice_unita_ordine'),
        ),
        migrations.AddConstraint(
            model_name='unitaproduzione',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__isnull', True), ('quantita__gte', 0), _connector='OR'), name='v2_quantita_unita_non_negativa'),
        ),
    ]
