# Generated by Django 6.1 on 2026-08-31 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0070_materiali_nc_tracciabilita'),
        ('produzione_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumomateriale',
            name='giacenza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impegni_produzione_v2', to='magazzino.giacenza'),
        ),
        migrations.AddField(
            model_name='consumomateriale',
            name='piano',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='consumomateriale',
            name='scaffale',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
