# Generated by Django 6.1 on 2026-08-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0002_consumomateriale_giacenza_consumomateriale_piano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformita',
            name='stato_fase_precedente',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='nonconformita',
            name='stato_ordine_precedente',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='nonconformita',
            name='stato_unita_precedente',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
