# Generated by Django 6.1 on 2026-08-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0070_materiali_nc_tracciabilita'),
        ('produzione_v2', '0003_nonconformita_stato_fase_precedente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versione', models.CharField(default='1', max_length=30)),
                ('quantita_riferimento', models.DecimalField(decimal_places=3, default=1, help_text='Quantità di prodotto a cui si riferiscono le quantità della ricetta.', max_digits=14)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cicli', to='produzione_v2.lineaproduzione')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cicli_produzione_v2', to='magazzino.articolo')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cicli_produzione_v2', to='magazzino.ricetta')),
            ],
            options={
                'ordering': ('prodotto__codice', 'versione'),
            },
        ),
        migrations.AddField(
            model_name='ordineproduzione',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='produzione_v2.cicloproduzione'),
        ),
        migrations.CreateModel(
            name='FabbisognoMateriale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_prevista', models.DecimalField(decimal_places=6, max_digits=14)),
                ('unita_misura', models.CharField(max_length=5)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabbisogni_produzione_v2', to='magazzino.articolo')),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabbisogni', to='produzione_v2.faseproduzione')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabbisogni', to='produzione_v2.ordineproduzione')),
                ('origine_ricetta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabbisogni_produzione_v2', to='magazzino.rigaricetta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cicloproduzione',
            constraint=models.UniqueConstraint(fields=('prodotto', 'versione'), name='v2_unico_ciclo_versione_prodotto'),
        ),
        migrations.AddConstraint(
            model_name='cicloproduzione',
            constraint=models.CheckConstraint(condition=models.Q(('quantita_riferimento__gt', 0)), name='v2_quantita_riferimento_ciclo_positiva'),
        ),
        migrations.AddConstraint(
            model_name='fabbisognomateriale',
            constraint=models.UniqueConstraint(fields=('ordine', 'articolo'), name='v2_unico_fabbisogno_articolo_ordine'),
        ),
        migrations.AddConstraint(
            model_name='fabbisognomateriale',
            constraint=models.CheckConstraint(condition=models.Q(('quantita_prevista__gt', 0)), name='v2_quantita_fabbisogno_positiva'),
        ),
    ]
