# Generated by Django 6.1 on 2026-08-31 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0004_cicloproduzione_ordineproduzione_ciclo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUnitaProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=100)),
                ('unita_misura', models.CharField(blank=True, max_length=10)),
                ('richiede_quantita', models.BooleanField(default=True)),
                ('attivo', models.BooleanField(default=True)),
                ('stazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipi_unita', to='produzione_v2.stazionelavoro')),
            ],
            options={
                'ordering': ('stazione', 'codice'),
            },
        ),
        migrations.AddField(
            model_name='unitaproduzione',
            name='tipo_definizione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unita', to='produzione_v2.tipounitaproduzione'),
        ),
        migrations.AddConstraint(
            model_name='tipounitaproduzione',
            constraint=models.UniqueConstraint(fields=('stazione', 'codice'), name='v2_unico_tipo_unita_stazione'),
        ),
    ]
