# Generated by Django 6.1 on 2026-08-31 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0070_materiali_nc_tracciabilita'),
        ('produzione_v2', '0005_tipounitaproduzione_unitaproduzione_tipo_definizione_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_lotto', models.CharField(max_length=50)),
                ('quantita', models.DecimalField(decimal_places=6, max_digits=14)),
                ('scaffale', models.CharField(blank=True, max_length=30)),
                ('piano', models.CharField(blank=True, max_length=30)),
                ('stato', models.CharField(choices=[('DICHIARATO', 'Dichiarato'), ('CARICATO', 'Caricato in magazzino'), ('ANNULLATO', 'Annullato')], default='DICHIARATO', max_length=10)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('caricato_il', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_produzione_v2', to='magazzino.articolo')),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_produzione_v2_creati', to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output', to='produzione_v2.faseproduzione')),
                ('lotto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_produzione_v2', to='magazzino.lotto')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output', to='produzione_v2.ordineproduzione')),
                ('ubicazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_produzione_v2', to='magazzino.ubicazione')),
                ('unita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output', to='produzione_v2.unitaproduzione')),
            ],
            options={
                'ordering': ('creato_il', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MovimentoOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('movimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collegamento_output_produzione_v2', to='magazzino.movimento')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collegamenti_movimento', to='produzione_v2.outputproduzione')),
            ],
        ),
        migrations.AddConstraint(
            model_name='outputproduzione',
            constraint=models.UniqueConstraint(fields=('articolo', 'codice_lotto'), name='v2_unico_output_lotto_articolo'),
        ),
        migrations.AddConstraint(
            model_name='outputproduzione',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__gt', 0)), name='v2_quantita_output_positiva'),
        ),
    ]
