# Generated by Django 6.1 on 2026-08-31 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0006_outputproduzione_movimentooutput_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stazionelavoro',
            name='richiede_operatore_abilitato',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AbilitazioneOperatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(blank=True, max_length=80)),
                ('valida_dal', models.DateField(default=django.utils.timezone.localdate)),
                ('valida_fino_al', models.DateField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abilitazioni_produzione_v2', to=settings.AUTH_USER_MODEL)),
                ('stazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abilitazioni_operatori', to='produzione_v2.stazionelavoro')),
            ],
            options={
                'ordering': ('stazione', 'operatore__username'),
                'constraints': [models.UniqueConstraint(fields=('operatore', 'stazione'), name='v2_unica_abilitazione_operatore_stazione')],
            },
        ),
    ]
