# Generated by Django 6.1 on 2026-08-31 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0007_stazionelavoro_richiede_operatore_abilitato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DipendenzaPassaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passaggio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dipendenze', to='produzione_v2.passaggiolinea')),
                ('predecessore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passaggi_successivi', to='produzione_v2.passaggiolinea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('passaggio', 'predecessore'), name='v2_unica_dipendenza_passaggio'), models.CheckConstraint(condition=models.Q(('passaggio', models.F('predecessore')), _negated=True), name='v2_dipendenza_passaggio_non_riflessiva')],
            },
        ),
    ]
