# Generated by Django 6.1 on 2026-09-01 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0008_dipendenzapassaggio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stazionelavoro',
            name='richiede_risorsa',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RisorsaProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('MACCHINA', 'Macchina'), ('AREA', 'Area di lavoro'), ('ATTREZZATURA', 'Attrezzatura')], max_length=15)),
                ('capacita', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unita_misura', models.CharField(blank=True, max_length=10)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('stazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risorse', to='produzione_v2.stazionelavoro')),
            ],
            options={
                'ordering': ('stazione', 'codice'),
            },
        ),
        migrations.CreateModel(
            name='ImpegnoRisorsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impegnata_il', models.DateTimeField(auto_now_add=True)),
                ('rilasciata_il', models.DateTimeField(blank=True, null=True)),
                ('assegnata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impegni_risorse_produzione_v2', to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impegni_risorse', to='produzione_v2.faseproduzione')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impegni', to='produzione_v2.risorsaproduzione')),
            ],
        ),
        migrations.AddConstraint(
            model_name='risorsaproduzione',
            constraint=models.CheckConstraint(condition=models.Q(('capacita__isnull', True), ('capacita__gt', 0), _connector='OR'), name='v2_capacita_risorsa_positiva'),
        ),
        migrations.AddConstraint(
            model_name='impegnorisorsa',
            constraint=models.UniqueConstraint(fields=('fase', 'risorsa'), name='v2_unico_impegno_risorsa_fase'),
        ),
    ]
