# Generated by Django 6.1 on 2026-09-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0009_stazionelavoro_richiede_risorsa_risorsaproduzione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faseproduzione',
            name='stato_pre_sospensione',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
