# Generated by Django 6.1 on 2026-09-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0010_faseproduzione_stato_pre_sospensione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordineproduzione',
            options={'ordering': ('-priorita', 'pianificato_per', 'codice'), 'permissions': [('configurare_produzione_v2', 'Può configurare linee, stazioni e cicli V2'), ('pianificare_produzione_v2', 'Può creare e pianificare ordini V2'), ('operare_produzione_v2', 'Può eseguire le fasi degli ordini V2'), ('gestire_qualita_v2', 'Può aprire e chiudere non conformità V2')]},
        ),
    ]
