# Generated by Django 6.1 on 2026-09-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0011_alter_ordineproduzione_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='faseproduzione',
            name='pianificata_fine',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faseproduzione',
            name='pianificata_inizio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passaggiolinea',
            name='durata_standard_minuti',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddConstraint(
            model_name='passaggiolinea',
            constraint=models.CheckConstraint(condition=models.Q(('durata_standard_minuti__gt', 0)), name='v2_durata_passaggio_positiva'),
        ),
    ]
