# Generated by Django 6.1 on 2026-09-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0012_faseproduzione_pianificata_fine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformita',
            name='decisione_flusso',
            field=models.CharField(blank=True, choices=[('PROSEGUE_TUTTI', 'Prosegue con tutti i batch'), ('SENZA_SCARTATI', 'Prosegue senza i batch scartati'), ('SOLO_REINTEGRATI', 'Prosegue solo con i batch reintegrati'), ('PRODUZIONE_ABORTITA', 'Produzione abortita')], max_length=21),
        ),
    ]
