# Generated by Django 6.1 on 2026-09-01 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0013_nonconformita_decisione_flusso'),
    ]

    operations = [
        migrations.AddField(
            model_name='rilevazionecontrollo',
            name='regole_applicate',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RegolaControlloCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regole', models.JSONField(default=dict)),
                ('attiva', models.BooleanField(default=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regole_controllo', to='produzione_v2.cicloproduzione')),
                ('definizione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regole_ciclo', to='produzione_v2.definizionecontrollo')),
            ],
            options={
                'ordering': ('definizione__stazione', 'definizione__ordine'),
                'constraints': [models.UniqueConstraint(fields=('ciclo', 'definizione'), name='v2_unica_regola_controllo_ciclo')],
            },
        ),
    ]
