# Generated by Django 6.1 on 2026-09-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0014_rilevazionecontrollo_regole_applicate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformita',
            name='rilevazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='produzione_v2.rilevazionecontrollo'),
        ),
    ]
