# Generated by Django 6.1 on 2026-09-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0070_materiali_nc_tracciabilita'),
        ('produzione_v2', '0015_nonconformita_rilevazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloproduzione',
            name='resa_massima_percentuale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cicloproduzione',
            name='resa_minima_percentuale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='nonconformita',
            name='tipo',
            field=models.CharField(choices=[('QUALITA', 'Controllo qualità'), ('UNITA', 'Unità produttiva'), ('MATERIALE', 'Materiale'), ('RESA', 'Resa produttiva'), ('ALTRO', 'Altro')], default='ALTRO', max_length=10),
        ),
        migrations.AddField(
            model_name='ordineproduzione',
            name='resa_massima_percentuale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ordineproduzione',
            name='resa_minima_percentuale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='cicloproduzione',
            constraint=models.CheckConstraint(condition=models.Q(('resa_minima_percentuale__isnull', True), ('resa_minima_percentuale__gte', 0), _connector='OR'), name='v2_resa_minima_non_negativa'),
        ),
        migrations.AddConstraint(
            model_name='cicloproduzione',
            constraint=models.CheckConstraint(condition=models.Q(('resa_massima_percentuale__isnull', True), ('resa_massima_percentuale__gte', 0), _connector='OR'), name='v2_resa_massima_non_negativa'),
        ),
    ]
