# Generated by Django 6.1 on 2026-09-01 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0016_cicloproduzione_resa_massima_percentuale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_settimana', models.PositiveSmallIntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('attivo', models.BooleanField(default=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turni', to='produzione_v2.lineaproduzione')),
            ],
            options={
                'ordering': ('linea', 'giorno_settimana', 'ora_inizio'),
                'constraints': [models.UniqueConstraint(fields=('linea', 'giorno_settimana', 'ora_inizio', 'ora_fine'), name='v2_unico_turno_linea'), models.CheckConstraint(condition=models.Q(('ora_fine__gt', models.F('ora_inizio'))), name='v2_turno_fine_dopo_inizio')],
            },
        ),
    ]
