# Generated by Django 6.1 on 2026-09-01 20:49

import django.utils.timezone
import hashlib
import json
from django.db import migrations, models


def firma_eventi_esistenti(apps, schema_editor):
    Evento = apps.get_model('produzione_v2', 'EventoProduzione')
    ordini = Evento.objects.values_list('ordine_id', flat=True).distinct()
    for ordine_id in ordini:
        precedente = ''
        for evento in Evento.objects.filter(ordine_id=ordine_id).order_by('registrato_il', 'id'):
            contenuto = {
                'ordine_id': evento.ordine_id,
                'fase_id': evento.fase_id,
                'tipo': evento.tipo,
                'dati': evento.dati,
                'registrato_il': evento.registrato_il.isoformat(),
                'operatore_id': evento.operatore_id,
                'hash_precedente': precedente,
            }
            serializzato = json.dumps(
                contenuto, sort_keys=True, separators=(',', ':'),
                ensure_ascii=False, default=str,
            )
            firma = hashlib.sha256(serializzato.encode('utf-8')).hexdigest()
            Evento.objects.filter(pk=evento.pk).update(
                hash_precedente=precedente, hash_evento=firma,
            )
            precedente = firma


class Migration(migrations.Migration):

    dependencies = [
        ('produzione_v2', '0017_turnolinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoproduzione',
            name='hash_evento',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='eventoproduzione',
            name='hash_precedente',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='eventoproduzione',
            name='registrato_il',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RunPython(firma_eventi_esistenti, migrations.RunPython.noop),
    ]
