# Generated by Django 6.1 on 2026-08-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30, unique=True)),
                ('descrizione', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('MATERIA_PRIMA', 'Materia prima'), ('MOCA', 'MOCA'), ('IGIENE', 'Igiene'), ('SEMILAVORATO', 'Semilavorato'), ('PACKAGING', 'Packaging'), ('PRODOTTO_FINITO', 'Prodotto finito')], max_length=20)),
                ('unita_misura', models.CharField(choices=[('KG', 'Kilogrammi'), ('L', 'Litri'), ('PZ', 'Pezzi')], max_length=5)),
                ('scorta_minima', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('criterio_rotazione', models.CharField(choices=[('FIFO', 'FIFO'), ('FEFO', 'FEFO'), ('NESSUNO', 'Nessuno')], default='FIFO', max_length=10)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
