# Generated by Django 6.1 on 2026-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo_magazzino', models.CharField(choices=[('MP', 'Materie prime'), ('IGIENE', 'Igiene'), ('MOCA', 'MOCA'), ('SEMILAVORATI', 'Semilavorati'), ('PRODUZIONE', 'Produzione'), ('PACKAGING', 'Packaging'), ('PRODOTTI_FINITI', 'Prodotti finiti')], max_length=20)),
                ('scaffale', models.CharField(blank=True, max_length=30)),
                ('piano', models.CharField(blank=True, max_length=30)),
                ('attiva', models.BooleanField(default=True)),
            ],
        ),
    ]
