# Generated by Django 6.1 on 2026-08-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_ubicazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_lotto', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('ACQUISTO', 'Acquisto'), ('PRODUZIONE', 'Produzione')], max_length=15)),
                ('fornitore', models.CharField(blank=True, max_length=200)),
                ('data_arrivo', models.DateField(blank=True, null=True)),
                ('data_produzione', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('quantita_iniziale', models.DecimalField(decimal_places=3, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotti', to='magazzino.articolo')),
            ],
        ),
    ]
