# Generated by Django 6.1 on 2026-08-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0003_lotto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giacenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giacenze', to='magazzino.lotto')),
                ('ubicazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giacenze', to='magazzino.ubicazione')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lotto', 'ubicazione'), name='unica_giacenza_lotto_ubicazione')],
            },
        ),
    ]
