# Generated by Django 6.1 on 2026-08-24 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0004_giacenza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('CARICO', 'Carico'), ('TRASFERIMENTO', 'Trasferimento'), ('CONSUMO', 'Consumo'), ('PRODUZIONE', 'Produzione'), ('PACKAGING', 'Packaging'), ('RICONFEZIONAMENTO', 'Riconfezionamento'), ('VENDITA', 'Vendita'), ('RETTIFICA', 'Rettifica')], max_length=25)),
                ('quantita', models.DecimalField(decimal_places=3, max_digits=12)),
                ('causale', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='magazzino.lotto')),
                ('ubicazione_destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_destinazione', to='magazzino.ubicazione')),
                ('ubicazione_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_origine', to='magazzino.ubicazione')),
            ],
        ),
    ]
