# Generated by Django 6.1 on 2026-08-24 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0005_movimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30, unique=True)),
                ('ragione_sociale', models.CharField(max_length=200)),
                ('partita_iva', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('indirizzo', models.CharField(blank=True, max_length=250)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lotto',
            name='fornitore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotti', to='magazzino.fornitore'),
        ),
    ]
