# Generated by Django 6.1 on 2026-08-24 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0006_fornitore_alter_lotto_fornitore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ricetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('versione', models.CharField(default='1', max_length=30)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ricette', to='magazzino.articolo')),
            ],
        ),
        migrations.CreateModel(
            name='RigaRicetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=6, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe_ricetta', to='magazzino.articolo')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='magazzino.ricetta')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ricetta', 'articolo'), name='unico_articolo_per_ricetta')],
            },
        ),
    ]
