# Generated by Django 6.1 on 2026-08-25 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0008_alter_articolo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_prodotta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('data_produzione', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('articolo', models.ForeignKey(limit_choices_to={'categoria': 'PRODOTTO_QUASI_FINITO'}, on_delete=django.db.models.deletion.PROTECT, related_name='produzioni', to='magazzino.articolo')),
                ('lotto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='produzione', to='magazzino.lotto')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_utilizzata', models.DecimalField(decimal_places=3, max_digits=12)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumi_produzione', to='magazzino.lotto')),
                ('ubicazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumi_produzione', to='magazzino.ubicazione')),
                ('produzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumi', to='magazzino.produzione')),
            ],
        ),
    ]
