# Generated by Django 6.1 on 2026-08-25 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0009_produzione_consumoproduzione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produzione',
            name='articolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produzioni', to='magazzino.articolo'),
        ),
    ]
