# Generated by Django 6.1 on 2026-08-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0010_alter_produzione_articolo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.UniqueConstraint(fields=('articolo', 'codice_lotto'), name='unico_lotto_per_articolo'),
        ),
    ]
