# Generated by Django 6.1 on 2026-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0011_lotto_unico_lotto_per_articolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoproduzione',
            name='quantita_utilizzata',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='giacenza',
            name='quantita',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lotto',
            name='quantita_iniziale',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='quantita',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='produzione',
            name='quantita_prodotta',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
