# Generated by Django 6.1 on 2026-08-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0012_alter_consumoproduzione_quantita_utilizzata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confezionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_confezionata', models.DecimalField(decimal_places=6, max_digits=12)),
                ('data_confezionamento', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('articolo_finito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confezionamenti', to='magazzino.articolo')),
                ('lotto_finito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confezionamento', to='magazzino.lotto')),
                ('lotto_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confezionamenti_origine', to='magazzino.lotto')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoConfezionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_utilizzata', models.DecimalField(decimal_places=6, max_digits=12)),
                ('confezionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumi', to='magazzino.confezionamento')),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumi_confezionamento', to='magazzino.lotto')),
                ('ubicazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumi_confezionamento', to='magazzino.ubicazione')),
            ],
        ),
    ]
