# Generated by Django 6.1 on 2026-08-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0013_confezionamento_consumoconfezionamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='categoria',
            field=models.CharField(choices=[('MATERIA_PRIMA', 'Materia prima'), ('MOCA', 'MOCA'), ('IGIENE', 'Igiene'), ('SEMILAVORATO', 'Semilavorato'), ('PACKAGING', 'Packaging'), ('PRODOTTO_FINITO', 'Prodotto finito')], max_length=25),
        ),
    ]
