# Generated by Django 6.1 on 2026-08-25 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0014_alter_articolo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confezionamento',
            name='lotto_finito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confezionamenti_destinazione', to='magazzino.lotto'),
        ),
    ]
