# Generated by Django 6.1 on 2026-08-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0015_alter_confezionamento_lotto_finito'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='tipo_packaging',
            field=models.CharField(blank=True, choices=[('ETICHETTA', 'Etichetta'), ('SCATOLA', 'Scatola'), ('COFANETTO', 'Cofanetto'), ('ALTRO', 'Altro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='categoria',
            field=models.CharField(choices=[('MATERIA_PRIMA', 'Materia prima'), ('MOCA', 'MOCA'), ('IGIENE', 'Igiene'), ('SEMILAVORATO', 'Semilavorato'), ('PACKAGING', 'Packaging'), ('PRODOTTO_NUDO', 'Prodotto nudo'), ('PRODOTTO_FINITO', 'Prodotto finito')], max_length=25),
        ),
    ]
