# Generated by Django 6.1 on 2026-08-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0016_articolo_tipo_packaging_alter_articolo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='prodotto_finito_collegato',
            field=models.ForeignKey(blank=True, limit_choices_to={'categoria': 'PRODOTTO_FINITO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prodotti_nudi_collegati', to='magazzino.articolo'),
        ),
    ]
