# Generated by Django 6.1 on 2026-08-25 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0017_articolo_prodotto_finito_collegato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscatolamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_prodotti', models.DecimalField(decimal_places=6, max_digits=12)),
                ('quantita_imballi', models.DecimalField(decimal_places=6, max_digits=12)),
                ('pezzi_per_imballo', models.PositiveIntegerField()),
                ('data_inscatolamento', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('lotto_imballo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilizzi_inscatolamento', to='magazzino.lotto')),
                ('lotto_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscatolamenti', to='magazzino.lotto')),
            ],
        ),
    ]
