# Generated by Django 6.1 on 2026-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0018_inscatolamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='pezzi_per_imballo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
