# Generated by Django 6.1 on 2026-08-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0019_articolo_pezzi_per_imballo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduzioneSemilavorato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_produzione', models.DateField()),
                ('quantita_prodotta', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('CONFERMATA', 'Confermata')], default='BOZZA', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('articolo', models.ForeignKey(limit_choices_to={'categoria': 'SEMILAVORATO'}, on_delete=django.db.models.deletion.PROTECT, related_name='produzioni_semilavorato', to='magazzino.articolo')),
                ('lotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produzioni_semilavorato', to='magazzino.lotto')),
                ('ubicazione_destinazione', models.ForeignKey(blank=True, limit_choices_to={'tipo_magazzino': 'SEMILAVORATI'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produzioni_semilavorato_destinazione', to='magazzino.ubicazione')),
            ],
        ),
        migrations.CreateModel(
            name='PrelievoProduzioneSemilavorato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_prelevata', models.DecimalField(decimal_places=6, max_digits=12)),
                ('quantita_residua', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelievi_produzione_semilavorato', to='magazzino.lotto')),
                ('ubicazione_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelievi_produzione_semilavorato', to='magazzino.ubicazione')),
                ('produzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelievi', to='magazzino.produzionesemilavorato')),
            ],
        ),
    ]
