# Generated by Django 6.1 on 2026-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0020_produzionesemilavorato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelievoproduzionesemilavorato',
            name='quantita_residua',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=12, null=True),
        ),
    ]
