# Generated by Django 6.1 on 2026-08-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0021_alter_prelievoproduzionesemilavorato_quantita_residua'),
    ]

    operations = [
        migrations.AddField(
            model_name='produzione',
            name='stato',
            field=models.CharField(choices=[('BOZZA', 'Bozza'), ('CONFERMATA', 'Confermata')], default='BOZZA', max_length=15),
        ),
        migrations.AddField(
            model_name='produzione',
            name='ubicazione_destinazione',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_magazzino': 'PACKAGING'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produzioni_destinazione', to='magazzino.ubicazione'),
        ),
        migrations.AlterField(
            model_name='produzione',
            name='articolo',
            field=models.ForeignKey(limit_choices_to={'categoria': 'PRODOTTO_NUDO'}, on_delete=django.db.models.deletion.PROTECT, related_name='produzioni', to='magazzino.articolo'),
        ),
        migrations.AlterField(
            model_name='produzione',
            name='lotto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produzione', to='magazzino.lotto'),
        ),
        migrations.AlterField(
            model_name='produzione',
            name='quantita_prodotta',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PrelievoProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_prelevata', models.DecimalField(decimal_places=6, max_digits=12)),
                ('quantita_residua', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelievi_produzione', to='magazzino.lotto')),
                ('produzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelievi', to='magazzino.produzione')),
                ('ubicazione_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelievi_produzione', to='magazzino.ubicazione')),
            ],
        ),
        migrations.DeleteModel(
            name='ConsumoProduzione',
        ),
    ]
