# Generated by Django 6.1 on 2026-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0022_produzione_stato_produzione_ubicazione_destinazione_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prelievoproduzionesemilavorato',
            name='quantita_residua',
        ),
        migrations.AddField(
            model_name='prelievoproduzionesemilavorato',
            name='quantita_scarto',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=12, null=True),
        ),
    ]
