# Generated by Django 6.1 on 2026-08-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0023_remove_prelievoproduzionesemilavorato_quantita_residua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigaricetta',
            name='ingrediente_prodotto',
            field=models.BooleanField(default=True),
        ),
    ]
