# Generated by Django 6.1 on 2026-08-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0024_rigaricetta_ingrediente_prodotto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prelievoproduzione',
            name='quantita_residua',
        ),
        migrations.AddField(
            model_name='prelievoproduzione',
            name='quantita_scarto',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=12, null=True),
        ),
    ]
