# Generated by Django 6.1 on 2026-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0044_registro_operazioni_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotto',
            name='ddt',
            field=models.CharField(blank=True, max_length=100, verbose_name='DDT'),
        ),
        migrations.AddField(
            model_name='lotto',
            name='fattura',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lotto',
            name='numero_colli',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotto',
            name='peso_unita_acquisto',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lotto',
            name='unita_acquisto_per_collo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.CheckConstraint(condition=models.Q(('numero_colli__isnull', True), ('numero_colli__gt', 0), _connector='OR'), name='lotto_numero_colli_positivo'),
        ),
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.CheckConstraint(condition=models.Q(('unita_acquisto_per_collo__isnull', True), ('unita_acquisto_per_collo__gt', 0), _connector='OR'), name='lotto_uda_per_collo_positive'),
        ),
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.CheckConstraint(condition=models.Q(('peso_unita_acquisto__isnull', True), ('peso_unita_acquisto__gt', 0), _connector='OR'), name='lotto_peso_uda_positivo'),
        ),
    ]
