# Generated by Django 6.1 on 2026-08-28 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crea_ruolo_qualita(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    content_type, _ = ContentType.objects.get_or_create(
        app_label="magazzino",
        model="nonconformitalotto",
    )
    permission, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename="gestire_non_conformita",
        defaults={
            "name": "Può decidere scarto e reintegro delle non conformità",
        },
    )
    gruppo, _ = Group.objects.get_or_create(name="Responsabili qualità")
    gruppo.permissions.add(permission)


def elimina_ruolo_qualita(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Responsabili qualità").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0045_documenti_struttura_acquisto_lotto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('CARICO', 'Carico'), ('TRASFERIMENTO', 'Trasferimento'), ('CONSUMO', 'Consumo'), ('PRODUZIONE', 'Produzione'), ('PACKAGING', 'Packaging'), ('RICONFEZIONAMENTO', 'Riconfezionamento'), ('VENDITA', 'Vendita'), ('RETTIFICA', 'Rettifica'), ('QUARANTENA', 'Quarantena per non conformità'), ('REINTEGRO', 'Reintegro da quarantena'), ('SCARTO_NC', 'Scarto per non conformità')], max_length=25),
        ),
        migrations.CreateModel(
            name='NonConformitaLotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('CHIUSA', 'Chiusa')], db_index=True, default='APERTA', max_length=10)),
                ('scaffale_origine', models.CharField(blank=True, max_length=30)),
                ('piano_origine', models.CharField(blank=True, max_length=30)),
                ('numero_uda_quarantena', models.PositiveIntegerField()),
                ('quantita_quarantena', models.DecimalField(decimal_places=6, max_digits=12)),
                ('quantita_per_uda', models.DecimalField(decimal_places=6, max_digits=12)),
                ('motivo', models.TextField()),
                ('note_apertura', models.TextField(blank=True)),
                ('data_apertura', models.DateTimeField(auto_now_add=True)),
                ('numero_uda_scartate', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_uda_reintegrate', models.PositiveIntegerField(blank=True, null=True)),
                ('decisione', models.TextField(blank=True)),
                ('data_chiusura', models.DateTimeField(blank=True, null=True)),
                ('aperta_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita_aperte', to=settings.AUTH_USER_MODEL)),
                ('gestita_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita_gestite', to=settings.AUTH_USER_MODEL)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='magazzino.lotto')),
                ('ubicazione_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita_lotti', to='magazzino.ubicazione')),
            ],
            options={
                'ordering': ('-data_apertura', '-id'),
                'permissions': [('gestire_non_conformita', 'Può decidere scarto e reintegro delle non conformità')],
                'constraints': [models.CheckConstraint(condition=models.Q(('numero_uda_quarantena__gt', 0)), name='nc_numero_uda_quarantena_positivo'), models.CheckConstraint(condition=models.Q(('quantita_quarantena__gt', 0)), name='nc_quantita_quarantena_positiva'), models.CheckConstraint(condition=models.Q(('quantita_per_uda__gt', 0)), name='nc_quantita_per_uda_positiva')],
            },
        ),
        migrations.RunPython(crea_ruolo_qualita, elimina_ruolo_qualita),
    ]
