# Generated by Django 6.1 on 2026-08-28 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0046_non_conformita_lotti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nonconformitalotto',
            name='nc_numero_uda_quarantena_positivo',
        ),
        migrations.RemoveConstraint(
            model_name='nonconformitalotto',
            name='nc_quantita_quarantena_positiva',
        ),
        migrations.RemoveConstraint(
            model_name='nonconformitalotto',
            name='nc_quantita_per_uda_positiva',
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='ambito',
            field=models.CharField(choices=[('PRODUZIONE', 'Produzione'), ('COMMERCIALE', 'Commerciale')], db_index=True, default='PRODUZIONE', max_length=15),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='analisi_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='azione_immediata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='azione_risoluzione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='data_inizio_gestione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='data_verifica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='esito_efficacia',
            field=models.CharField(blank=True, choices=[('EFFICACE', 'Efficace'), ('NON_EFFICACE', 'Non efficace'), ('NON_APPLICABILE', 'Non applicabile')], max_length=20),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='responsabile_azione',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='scadenza_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='tipo_nc',
            field=models.CharField(choices=[('RECLAMO_CLIENTE', 'Reclamo del Cliente'), ('VERSO_FORNITORE', 'Verso fornitore'), ('INTERNO', 'Interno (Processo/Prodotto)'), ('STRUTTURALE', 'Strutturale'), ('ALTRO', 'Altro')], db_index=True, default='INTERNO', max_length=25),
        ),
        migrations.AddField(
            model_name='nonconformitalotto',
            name='verifica_efficacia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nonconformitalotto',
            name='lotto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='magazzino.lotto'),
        ),
        migrations.AlterField(
            model_name='nonconformitalotto',
            name='numero_uda_quarantena',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonconformitalotto',
            name='quantita_per_uda',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='nonconformitalotto',
            name='quantita_quarantena',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='nonconformitalotto',
            name='stato',
            field=models.CharField(choices=[('APERTA', 'Aperta'), ('IN_LAVORAZIONE', 'In lavorazione'), ('CHIUSA', 'Chiusa')], db_index=True, default='APERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='nonconformitalotto',
            name='ubicazione_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita_lotti', to='magazzino.ubicazione'),
        ),
        migrations.AddConstraint(
            model_name='nonconformitalotto',
            constraint=models.CheckConstraint(condition=models.Q(('numero_uda_quarantena__isnull', True), ('numero_uda_quarantena__gt', 0), _connector='OR'), name='nc_numero_uda_quarantena_positivo'),
        ),
        migrations.AddConstraint(
            model_name='nonconformitalotto',
            constraint=models.CheckConstraint(condition=models.Q(('quantita_quarantena__isnull', True), ('quantita_quarantena__gt', 0), _connector='OR'), name='nc_quantita_quarantena_positiva'),
        ),
        migrations.AddConstraint(
            model_name='nonconformitalotto',
            constraint=models.CheckConstraint(condition=models.Q(('quantita_per_uda__isnull', True), ('quantita_per_uda__gt', 0), _connector='OR'), name='nc_quantita_per_uda_positiva'),
        ),
    ]
