# Generated by Django 6.1 on 2026-08-28 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0047_registro_generale_non_conformita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produzione',
            name='fase',
            field=models.CharField(choices=[('PREPARAZIONE', 'Preparazione'), ('ROBOQUBO', 'RoboQubo'), ('INVASETTAMENTO', 'Invasettamento'), ('COMPLETATA', 'Completata')], default='PREPARAZIONE', max_length=20),
        ),
        migrations.AddField(
            model_name='produzione',
            name='lotto_provvisorio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='produzione',
            name='moca_igienizzati',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produzione',
            name='moca_igienizzati_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produzioni_moca_igienizzati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produzione',
            name='moca_igienizzati_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produzione',
            name='numero_batch_previsti',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produzione',
            name='preparazione_chiusa_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produzione',
            name='roboqubo_chiuso_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tankproduzione',
            name='chiuso_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BatchProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('temperatura_conformita', models.DecimalField(decimal_places=2, default=82, max_digits=5)),
                ('durata_conformita_secondi', models.PositiveSmallIntegerField(default=60)),
                ('esito_conformita', models.CharField(choices=[('C', 'Conforme'), ('NC', 'Non conforme'), ('NA', 'Non applicabile')], max_length=2)),
                ('note', models.TextField(blank=True)),
                ('registrato_il', models.DateTimeField(auto_now_add=True)),
                ('produzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='magazzino.produzione')),
                ('registrato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='magazzino.tankproduzione')),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('produzione', 'numero'), name='unico_batch_per_produzione')],
            },
        ),
        migrations.CreateModel(
            name='CarrelloProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('numero_pezzi', models.PositiveIntegerField()),
                ('temperatura_pastorizzazione', models.DecimalField(decimal_places=2, default=71, max_digits=5)),
                ('durata_pastorizzazione_minuti', models.PositiveSmallIntegerField(default=4)),
                ('esito_pastorizzazione', models.CharField(choices=[('C', 'Conforme'), ('NC', 'Non conforme'), ('NA', 'Non applicabile')], max_length=2)),
                ('note_pastorizzazione', models.TextField(blank=True)),
                ('pastorizzazione_registrata_il', models.DateTimeField(auto_now_add=True)),
                ('esito_shock_vuoto', models.CharField(blank=True, choices=[('C', 'Conforme'), ('NC', 'Non conforme'), ('NA', 'Non applicabile')], max_length=2)),
                ('pezzi_difettosi', models.PositiveIntegerField(default=0)),
                ('note_shock_vuoto', models.TextField(blank=True)),
                ('shock_vuoto_registrato_il', models.DateTimeField(blank=True, null=True)),
                ('capsule_difettose', models.PositiveIntegerField(blank=True, null=True)),
                ('chiuso_il', models.DateTimeField(blank=True, null=True)),
                ('produzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrelli', to='magazzino.produzione')),
                ('registrato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('produzione', 'numero'), name='unico_carrello_per_produzione')],
            },
        ),
    ]
