# Generated by Django 6.1 on 2026-08-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0048_flusso_produzione_tre_fasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrelloproduzione',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrelli', to='magazzino.tankproduzione'),
        ),
    ]
