# Generated by Django 6.1 on 2026-08-28 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0049_carrello_collegato_tank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchproduzione',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='magazzino.tankproduzione'),
        ),
        migrations.AlterField(
            model_name='carrelloproduzione',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrelli', to='magazzino.tankproduzione'),
        ),
    ]
