# Generated by Django 6.1 on 2026-08-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0050_elimina_produzione_con_batch_carrelli'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelievoproduzione',
            name='quantita_movimentata',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Quantità fisicamente prelevata in UDA intere.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prelievoproduzione',
            name='quantita_resa_produzione',
            field=models.DecimalField(decimal_places=6, default=0, help_text="Avanzo dell'UDA trasferito al Magazzino produzione.", max_digits=12),
        ),
        migrations.AddField(
            model_name='produzione',
            name='capsule_difettose_finali',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produzione',
            name='difetti_registrati_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produzione',
            name='pezzi_difettosi_finali',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrelloproduzione',
            name='numero_pezzi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
