# Generated by Django 6.1 on 2026-08-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0051_prelievoproduzione_quantita_movimentata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produzione',
            name='peso_netto_vasetto_g',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
