# Generated by Django 6.1 on 2026-08-29 06:37

from django.db import migrations, models


def disattiva_tracciabilita_igiene(apps, schema_editor):
    Articolo = apps.get_model("magazzino", "Articolo")
    Articolo.objects.filter(categoria="IGIENE").update(tracciabilita_lotto=False)


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0052_produzione_peso_netto_vasetto_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='tracciabilita_lotto',
            field=models.BooleanField(default=True, help_text='Se disattivata, MIRA genera un riferimento interno senza chiedere il lotto.'),
        ),
        migrations.RunPython(
            disattiva_tracciabilita_igiene,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='articolo',
            name='categoria',
            field=models.CharField(choices=[('MATERIA_PRIMA', 'Materia prima'), ('MOCA', 'MOCA'), ('IGIENE', 'Igiene'), ('SEMILAVORATO', 'Semilavorato'), ('PACKAGING', 'Packaging'), ('CONSUMABILI', 'Consumabili'), ('PRODOTTO_FINITO', 'Prodotto finito')], max_length=25),
        ),
    ]
