# Generated by Django 6.1 on 2026-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0053_articolo_tracciabilita_lotto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produzione',
            options={'permissions': [('gestire_produzioni', 'Può verificare e correggere le produzioni')]},
        ),
        migrations.RemoveField(
            model_name='carrelloproduzione',
            name='tank',
        ),
        migrations.AddField(
            model_name='produzione',
            name='quantita_teorica_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='produzione',
            name='resa_percentuale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
