# Generated by Django 6.1 on 2026-08-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0054_alter_produzione_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produzione',
            options={'permissions': [('operare_roboqubo', 'Può registrare i cicli RoboQubo'), ('operare_invasettamento', "Può registrare l'invasettamento"), ('gestire_produzioni', 'Può verificare e correggere le produzioni')]},
        ),
    ]
